
module.exports = {
  '0x50':	"transfer failure",
  '0x51':	"transfer success",
  '0x52':	"insufficient balance",
  '0x53':	"insufficient allowance",
  '0x54':	"transfers halted (contract paused)",
  '0x55':	"funds locked (lockup period)",
  '0x56':	"invalid sender",
  '0x57':	"invalid receiver",
  '0x58': "invalid value",
  '0x59': "partition does not exist",
  '0x60': "invalid transfer lot size",
  '0x61': "invalid issuance (amount)",
  '0x62': "invalid issuance (granularity)",
  '0x63': "token not issuable",
  '0x64':	"invalid operator",
  '0x65':	"invalid controller",
  '0x66': "invalid issuer",
  '0x67': "invalid issuer or controller",
  '0x68': "invalid 0x00 address",
  '0x69': "invalid same address",
  '0x70': "document does not exist",
  '0x71': "partition can not change token owner",
  '0x72': "partition key already exists",
  '0x73': "partition already exists",
  '0x74': "invalid partition key",
  '0x75': "invalid certificate (params)",
  '0x76': "invalid certificate (nonce)",
  '0x77': "invalid certificate (token)",
  '0x78': "invalid certificate (controller)",
  '0x79': "should be at least two controllers"
}
